export const Constants = {
    CASH: "cash",
    BANK: "bank",
    CHEQUE: "cheque",
    UPI: "upi",
    CARD: "card",
    NETBENKING: "netbenking",
    PAID: 'paid',
    UNPAID: 'unpaid',
    PARTIAL_PAID: 'partial paid',
    TOTAL_SALE: 'total_sale',
    CUSTOMER: 'customer',
    PARTY: 'party',
    ITEM: 'item',
    PAY: 'pay',
    COLLECT: 'collect',
    CUSTOMER: 'customer',
    SUPPLIER: 'supplier',
    BOTHPARTY: 'both',
    TODAY: 'today',
    YESTERDAY: 'yesterday',
    LAST7DAY: 'last7day',
    LAST30DAY: 'last30day',
    LAST365DAY: 'last365day',
    THISWEEK: 'thisweek',
    LASTWEEK: 'lastweek',
    THISMONTH: 'thismonth',
    PREVMONTH: 'prevmonth',
    THISQUARTER: 'thisquarter',
    LASTQUARTER: 'lastquarter',
    CURRENTFISCAL: 'currentfiscal',
    LASTFISCAL: 'lastfiscal',
    CUSTOM: 'custom',
    GOODS: 'goods',
    SERVICE: 'service'
}